#!/bin/bash

CASTLEDIR=castle/castle*
for file in $CASTLEDIR; do
    echo @
    echo $file
    echo "optimal"
    (
        ulimit -t 60
        ulimit -v 2000000
        python3 fast-downward/fast-downward.py castle/domain.pddl $file --search "astar(lmcut())" --translate-options --relaxed
    )
    echo @
    echo @
    echo $file
    echo "ff"
    (
        ulimit -t 60
        ulimit -v 2000000
        python3 fast-downward/fast-downward.py $file --heuristic "h=ff()" --search "eager_greedy([h])"
    )
    echo @
    echo @
    echo $file
    echo "planopt_ff"
    (
        ulimit -t 60
        ulimit -v 2000000
        python3  fast-downward/fast-downward.py $file --heuristic "h=planopt_ff()" --search "eager_greedy([h])"
    )
    echo @
done